### ISSUE TITLE
3box<>IPLD Schemas

### ISSUE THREAD

**Issue by momack2** [ipld/roadmap#8]
Hey @oed - per your talk on the [IPFS All Hands ](https://www.youtube.com/watch?v=JFWi5yebR88&list=PLuhRWgmPaHtSGRSHdU9dbsukHKlihZZAe&index=2&t=0s) @warpfork has been working IPLD schemas and is continuing that this quarter. Shoot any Qs his way!

**Comment by oed** [comment]
Thanks @momack2! Currently reading up on this: https://github.com/ipld/specs/pull/113

**Comment by warpfork** [comment]
Catching up on that recording :)

> data schemas are really important

:100:

**Comment by oed** [comment]
@warpfork Any thoughts on compatibility on your work and schema.org and similar efforts?

**Comment by rvagg** [comment]
closing for archival
